---
# Poggit-Delta
#
# Copyright (C) 2018-2019 Poggit
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

sudo: required
language: node_js
env:
  global:
    - secure: "hz0z+H8ldFMiHi4gHjc05TM023ebVv2/nAVNwnbqtb//SpFTPItKwhLdX1owFALq+wVUwOlEAnFRmelYD76mEo7C8VvG4PFUUK1ur9lp8yXaXUJesKGbHIhMg7iWj3HEuiHt9MC79wcL2ITdufElZEPKc/v9ZY7bC4i8G3ryeCU4nbXdXRzwGkBgXN1KNaRlzxO13zlxxMqpvplbmyFIUjvP5rJYPZA8UZ87/VOut0ULryVZ3pmszmIKRR6iTemjXIRHw9LDiTFN3nAKXepaNabaGl99frtG8m5DHg35Zact3srzO/9l+ukd0ef/oITKLk2rS0eFtZKXeYhoEQgmqWi5A1GugGnaeOMZpEaNnLzmm83SfSRmu8TW6/hyJwVf2vyRe3Bt4UtOLJSBOWx3WyEcQY1olmiYnuLt36m6UABzwHdbLKNCgKlF9jeWOm9b4NfEcz3Sop8f6lW4sOAWQ0QHrurkFE26wlBprZt8H4SxNVrh+Uzqzj4Gc6I0hlGHt6G+1PUxGpojrzwuToLwZvxqnihIZqjgSWugBJDdgGPlwNiCBzkCkX2pQRkg8bGLHkxGsti448OYfvPyWzvRc8Ocqy6+KsIX9h/eJ8OKvszsDKnaWM4hEpG8N7sIPYcF8jl5Ta3BdUGqkbZbpx0DoNtremjEPeI/CvBHWDxSM4s="
    - secure: "DLBQ/fB6qyxrLk3dK3yRFNWPsWz9XGtosiSm9712zQLidV0ijjUS+r6TVnsESP8l9yzo46+oM4/6EtKaH3uAC5VrLQC2GgIT94LWB8qXO8QerWAIrz4JAXB/c8ANA5+eIMjzpthDj/VY6co7pBJ2hZypk6iTO/CEXCsnkIT2CHT4mZ9pM7cIZgd/aI/Ib6KlrgPVzyNU1c76TkUdYf3Ev3vP/L/4QXM89oBni+HTxEmoGhAzK9lJQXa+D2RPBC++R9F5khcVgakmDnWBE0sLD7sSWnGwOyUZZut+hTvTLDuOeuIPvqBUy1AcuOsbZsLG3iqH1UdSqXijVHCR+Jcj7txmRE5+UnbY5bLlzRWzuuokb7k5EwSkDrEIOuWqWvUoJBjtjgLI9Ilns1PtgN+xRrg/geKfBvcYGgDWIilVPGNyknDulvrFnqs2lLPYPavpMD8Q3QqpLWmoL8WBDL7GkUGwJbaMAgdmh4mJfUqCphuNqRKig85/LvOy+yVx6LzmcgtMYh28o74ydDd6ISY+rOOp8MlTV303Rhv8GhwcxCxDP+UXZuLqd7qLvjjFmTRXCO/yrsk4HHlqDKiUJf7KNophJSwHl1KgDBWxKD52pHpZn43r1WkILF02NL/s2SPjZ2FwnuFMQtkQFDQgADqBwrJu/SC3TBQjU+XgCjIeEUo="
services:
  - docker
node_js:
  - 8.14.0
before_install:
  - sudo apt-get update
  - sudo apt-get install -y jq make
install:
  - npm install -g typescript ts-node yaml2json mocha
  - docker pull mysql:8.0
  - docker pull node:8
  - docker pull sofe1970/yaml2json
before_script:
  - head -c16 /dev/urandom | base64 > mysql-password
  - touch wh.log frontend.log .server_started
  - stat -c %Y .server_started > .server_start_after
  - docker run -v `pwd`/default-docker-compose.yml:/input sofe1970/yaml2json yaml2json /input
        | jq ".services.mysql.environment.MYSQL_PASSWORD = \"$(cat mysql-password)\""
        | jq ".services.mysql.environment.MYSQL_ROOT_PASSWORD = \"$(cat mysql-password)\""
        | jq ".services.frontend.environment.PGD_DEBUG = \"true\""
        | jq ".services.wh.environment.PGD_DEBUG = \"true\""
        | jq ".services.mysql.restart = \"no\""
        | jq ".services.frontend.restart = \"no\""
        | jq ".services.wh.restart = \"no\""
        > docker-compose.yml
  - mkdir secrets && cp travis/secrets-import.js secrets/secrets.js
  - cat travis/secrets-default.json
        | jq ".database.password = \"$(cat mysql-password)\""
        > secrets/secrets.json
  - docker-compose build
script:
  - ./travis/testUnit.sh
  - docker-compose up -d
  - WAIT_SECONDS=0;
    while [[ `stat -c %Y .server_started` -eq `cat .server_start_after` ]]; do
      sleep 1;
      ((WAIT_SECONDS++));
      if [[ ${WAIT_SECONDS} -lt 120 ]]; then
        exit 1;
      fi;
    done
  - ./travis/populate.sh
  - ./travis/testIntegration.sh
after_failure:
  - docker-compose exec mysql bash -c "mysqldump -u \"\$MYSQL_USER\" -p\"\$MYSQL_PASSWORD\" \"\$MYSQL_DATABASE\""
  - docker-compose logs frontend
  - docker-compose logs wh
...
