language: rust
rust:
  - nightly
services:
  - docker
cache: cargo
install:
  - cargo fetch
  - nvm install v10.16.0
  - nvm use v10.16.0
  - npm install -g sass typescript parcel-bundler
  - make .build-deps
script:
  - make build
