---
# Poggit-Delta
#
# Copyright (C) 2018-2019 Poggit
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

language: nodejs
env:
  global:
    - secure: "hz0z+H8ldFMiHi4gHjc05TM023ebVv2/nAVNwnbqtb//SpFTPItKwhLdX1owFALq+wVUwOlEAnFRmelYD76mEo7C8VvG4PFUUK1ur9lp8yXaXUJesKGbHIhMg7iWj3HEuiHt9MC79wcL2ITdufElZEPKc/v9ZY7bC4i8G3ryeCU4nbXdXRzwGkBgXN1KNaRlzxO13zlxxMqpvplbmyFIUjvP5rJYPZA8UZ87/VOut0ULryVZ3pmszmIKRR6iTemjXIRHw9LDiTFN3nAKXepaNabaGl99frtG8m5DHg35Zact3srzO/9l+ukd0ef/oITKLk2rS0eFtZKXeYhoEQgmqWi5A1GugGnaeOMZpEaNnLzmm83SfSRmu8TW6/hyJwVf2vyRe3Bt4UtOLJSBOWx3WyEcQY1olmiYnuLt36m6UABzwHdbLKNCgKlF9jeWOm9b4NfEcz3Sop8f6lW4sOAWQ0QHrurkFE26wlBprZt8H4SxNVrh+Uzqzj4Gc6I0hlGHt6G+1PUxGpojrzwuToLwZvxqnihIZqjgSWugBJDdgGPlwNiCBzkCkX2pQRkg8bGLHkxGsti448OYfvPyWzvRc8Ocqy6+KsIX9h/eJ8OKvszsDKnaWM4hEpG8N7sIPYcF8jl5Ta3BdUGqkbZbpx0DoNtremjEPeI/CvBHWDxSM4s="
services:
  - docker
install:
  - apt-get install -y libghc-yaml-dev jq
  - npm install -g typescript ts-node
  - docker-compose build
before_script:
  - (echo -n \"; head -c16 /dev/urandom; echo -n \") | base64 > mysql-password
  - yaml2json default-docker-compose.yml
        | jq ".services.mysql.environment.MYSQL_PASSWORD = $(cat mysql-password)"
        | jq ".services.mysql.environment.MYSQL_ROOT_PASSWORD = $(cat mysql-password)"
        > docker-compose.yml
  - mkdir secrets && cp travis/secrets-import.js secrets/secrets.js
  - cat travis/secrets-default.json
        | jq ".database.password = $(cat mysql-password)"
        > secrets/secrets.json
script:
  - ./travis/testUnit.sh
  - docker-compose up &
  - ./travis/testIntegration.sh
  - docker-compose down
...
