# Poggit-Delta
#
# Copyright (C) 2018-2019 Poggit
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

version: "2"
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: correct horse battery staple
      MYSQL_USER: poggit
      MYSQL_PASSWORD: correct horse battery staple
      MYSQL_DATABASE: pgd
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
  wh:
    build: ./webhook-handler/docker/
    environment:
      TS_NODE_CACHE_DIRECTORY: /ts_cache
    restart: always
    links:
      - mysql:mysql
    volumes:
      - wh-npm-volume:/server/node_modules:rw
      - ./webhook-handler/src:/server/src:ro
      - ./webhook-handler/package.json:/server/package.json:ro
      - ./webhook-handler/package-lock.json:/sever/package-lock.json:ro
      - ./webhook-handler/run.sh:/run.sh:ro
      - ./secrets:/secrets:ro
      - ./shared:/shared:ro
      - wh-ts-cache:/ts_cache:rw
      - ./wh.log:/wh.log:rw
  frontend:
    build: ./frontend/docker/
    environment:
      TS_NODE_CACHE_DIRECTORY: /home/node/ex/ts_cache
    restart: always
    ports:
      - 80:3000
    links:
      - mysql:mysql
      - wh:wh
    volumes:
      - fe-client-npm-volume:/app/client/node_modules:rw
      - ./frontend/client/src:/app/client/src:ro
      - ./frontend/client/loader.js:/app/client/loader.js:ro
      - ./frontend/client/package.json:/app/client/package.json:ro
      - ./frontend/client/package-lock.json:/app/client/package-lock.json:ro
      - ./frontend/client/tsconfig.json:/app/client/tsconfig.json:ro
      - fe-server-npm-volume:/app/server/node_modules:rw
      - ./frontend/server/src:/app/server/src:ro
      - ./frontend/server/package.json:/app/server/package.json:ro
      - ./frontend/server/package-lock.json:/app/server/package-lock.json:ro
      - ./frontend/server/tsconfig.json:/app/server/tsconfig.json:ro
      - ./frontend/public:/app/public:ro
      - ./frontend/sass:/app/sass:ro
      - ./frontend/view:/app/view:ro
      - ./frontend/run.sh:/app/run.sh:ro
      - ./secrets:/secrets:ro
      - ./shared:/shared:ro
      - fe-ts-cache:/ts_cache:rw
      - ./frontend.log:/app/output.log
      - ./.server_started:/app/.server_started

volumes:
  mysql-volume: {}
  fe-server-npm-volume: {}
  fe-client-npm-volume: {}
  fe-ts-cache: {}
  wh-npm-volume: {}
  wh-ts-cache: {}
