version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: correct horse battery staple
      MYSQL_USER: poggit
      MYSQL_PASSWORD: correct horse battery staple
      MYSQL_DATABASE: poggit
    volumes:
      - mysql_data:/var/lib/mysql
    logging:
      driver: none
  wh:
    build: ./webhook/docker/
    environment:
      TS_NODE_CACHE_DIRECTORY: /ts_cache
    env_file:
      - ./docker.env
      - ./webhook/docker/docker.env
    links:
      - db:db
    volumes:
      - /ts_cache
      - /var/run/docker.sock:/var/run/docker.sock
      - ./webhook:/main
      - /main/docker
      - /main/node_modules
      - ./lib:/main/lib
      - /main/lib/all/node_modules
      - /main/lib/frontend/node_modules
      - /main/lib/server/node_modules
      - ./config.js:/main/config.js:ro
      - ./.started:/.started
  app:
    build: ./app/docker
    environment:
      TS_NODE_CACHE_DIRECTORY: /ts_cache
    env_file:
      - ./docker.env
      - ./app/docker/docker.env
    links:
      - db:db
      - wh:wh
    ports:
      - 21003:8002
    volumes:
      - /ts_cache
      - ./app:/main
      - /main/docker
      - /main/client/node_modules
      - /main/server/node_modules
      - ./lib:/main/lib
      - /main/lib/all/node_modules
      - /main/lib/frontend/node_modules
      - /main/lib/server/node_modules
      - ./config.js:/main/config.js:ro
      - ./.started:/.started

volumes:
  mysql_data: {}
