---
apiVersion: v1
kind: Namespace
metadata:
  name: poggit
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: poggit
  labels:
    name: poggit
    component: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      name: poggit
      component: mysql
  template:
    metadata:
      labels:
        name: poggit
        component: mysql
    spec:
      containers:
        - name: main
          image: mysql:5.7
          imagePullPolicy: Always
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: poggit
            - name: MYSQL_USER
              value: poggit
            - name: MYSQL_PASSWORD
              value: "123456"
          ports:
            - name: client
              containerPort: 3306
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        storageClassName: longhorn
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 16Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: poggit
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: client
      port: 3306
      targetPort: client
  selector:
    name: poggit
    component: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apache
  namespace: poggit
  labels:
    name: poggit
    component: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      name: poggit
      component: apache
  template:
    metadata:
      labels:
        name: poggit
        component: apache
    spec:
      containers:
        - name: main
          image: ghcr.io/poggit/poggit-apache
          imagePullPolicy: Always
          volumeMounts:
            - name: secrets
              mountPath: /poggit/secret
            - name: resources
              mountPath: /poggit/resources
            - name: logs
              mountPath: /poggit/logs
          ports:
            - name: http
              containerPort: 80
      volumes:
        - name: secrets
          configMap:
            name: poggit-secrets
  volumeClaimTemplates:
    - metadata:
        name: resources
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: longhorn
        resources:
          requests:
            storage: 64Gi
    - metadata:
        name: logs
      spec:
        storageClassName: local-path
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 16Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: poggit-secrets
  namespace: poggit
data:
  secrets.json: |
    {
        "mysql": {
            "host": "mysql.poggit.svc",
            "port": 3306,
            "user": "poggit",
            "password": "123456",
            "schema": "poggit"
        },
        "app": {
            "clientId": "Client ID from GitHub application",
            "clientSecret": "Client secret from GitHub application",
            "defaultToken": "A no-scope dummy-user access token used for GitHub API access when client is not logged in",
            "botToken": "An access token with the repo scope used for visible GitHub API access, such as comments"
        },
        "meta": {
            "intPath": "",
            "extPath": "https://poggit.pmmp.io/",
            "hookSecret": "Secure part of a secret for GitHub webhooks. Never change this value, or all webhooks will break.",
            "name": "poggitbot",
            "email": "poggitbot@gmail.com",
            "tmpPath": "/tmp/",
            "curl": {
                "timeout": 3,
                "perPage": 100
            },
            "debug": false,
            "debugPrefix": "",
            "testers": [],
            "access": {}
        },
        "perms": {
            "submoduleQuota": {
                "69691727": 10
            },
            "projectQuota": {},
            "buildQuota": {
                "1": 1000
            },
            "bans": {
                "1": "mojombo, you are one of the founders of GitHub, so I have to thank you by banning you on a website you'd never visit"
            },
            "ipBans": {
                "127.0.0.1": "Remember to edit the secrets.json!"
            }
        },
        "tryServerEndpoints": [
        ],
        "discord": {
            "serverInvite": "https://discord.gg/NgHf9jt",
            "pluginUpdatesHook": "https://discordapp.com/api/webhooks/1/A",
            "newBuildsHook": "https://discordapp.com/api/webhooks/2/B",
            "errorHook": "https://discordapp.com/api/webhooks/3/C",
            "reviewHook": "https://discordapp.com/api/webhooks/4/D",
            "reviewsHook": "https://discordapp.com/api/webhooks/5/E",
            "regHook": "https://discordapp.com/api/webhooks/6/F",
            "throttleHook": "https://discordapp.com/api/webhooks/7/G"
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: poggit
  namespace: poggit
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    name: poggit
    component: apache
