version: "2"
services:
  db:
    image: postgres:12
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    env_file:
      - .env
  backend:
    build: docker/backend
    volumes:
      - ./target/debug/backend:/main/main
      - ./.env:/main/.env
    links:
      - db:db
    env_file:
      - .env
  builder:
    build: docker/builder
    volumes:
      - ./target/debug/builder:/main/main
      - ./key.pem:/main/key.pem
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/main/.env
    links:
      - backend:backend
  plugins:
    build: docker/default
    volumes:
      - ./target/debug/plugins:/main/main
      - ./.env:/main/.env
    links:
      - backend:backend
  ci:
    build: docker/default
    volumes:
      - ./target/debug/ci:/main/main
      - ./.env:/main/.env
    links:
      - backend:backend
  proxy:
    build: docker/default
    volumes:
      - ./target/debug/proxy:/main/main
      - ./.env:/main/.env
    links:
      - backend:backend
