[package]
name = "common"
version = "2.0.0"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
config = ""
dotenv = ""
graphql_client = {version = "", optional = true}
log = ""
env_logger = ""
serde = ""
serde_derive = ""

[features]
default = []
client = ["graphql_client"]
